import { ServiceCategory } from './types';

export const MAKURDI_AREAS = [
  'Wurukum',
  'High Level',
  'North Bank',
  'Kanshio',
  'Apir',
  'Modern Market',
  'Nyiman',
  'Fiidi',
  'Low Level',
  'Judges Quarters',
  'Wadata',
  'Old GRA',
  'New GRA',
  'Customs Barracks',
  'George Akume Way',
  'BSU Area',
  'UniAgric Road',
  'Air Force Base Road',
];

export const NIGERIAN_CITIES = [
  'Makurdi',
  'Gboko',
  'Otukpo',
  'Abuja (FCT)',
  'Lagos',
  'Jos',
  'Enugu',
];

export const NIGERIAN_BANKS = [
  { name: 'First Bank of Nigeria', code: '011' },
  { name: 'Access Bank', code: '044' },
  { name: 'Guaranty Trust Bank (GTBank)', code: '058' },
  { name: 'United Bank for Africa (UBA)', code: '033' },
  { name: 'Zenith Bank', code: '057' },
  { name: 'Fidelity Bank', code: '070' },
  { name: 'Union Bank of Nigeria', code: '032' },
  { name: 'Stanbic IBTC Bank', code: '221' },
  { name: 'Ecobank Nigeria', code: '050' },
  { name: 'Kuda Bank', code: '50211' },
  { name: 'Moniepoint Microfinance Bank', code: '50515' },
  { name: 'OPay Digital Services', code: '999992' },
  { name: 'Palmpay', code: '999991' },
];

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  { id: 'cat-plumbing', name: 'Plumbing', iconName: 'Wrench', description: 'Piping, leak detection, water pump install, and bathroom fitting', active: true },
  { id: 'cat-electrical', name: 'Electrical', iconName: 'Zap', description: 'Wiring, conduit, inverter & solar power, distribution boards', active: true },
  { id: 'cat-generator', name: 'Generator Repair', iconName: 'Cpu', description: 'Elepaq, Sumec Firman, Tiger, Mikano, Perkins servicing', active: true },
  { id: 'cat-ac-refrig', name: 'Air Conditioner & Refrigeration', iconName: 'Snowflake', description: 'AC gas refills, chilling systems, deep freezers, compressor fixes', active: true },
  { id: 'cat-carpentry', name: 'Carpentry & Roofing', iconName: 'Hammer', description: 'Roof truss, wood framing, doors, partitions, and decking', active: true },
  { id: 'cat-furniture', name: 'Furniture Making', iconName: 'Armchair', description: 'Custom sofa sets, royal dining, wardrobes, and office desks', active: true },
  { id: 'cat-pop-ceiling', name: 'POP & Ceiling Installation', iconName: 'Layers', description: 'Gypsum board, modern POP designs, cornices, and screeding', active: true },
  { id: 'cat-tiling', name: 'Tiling & Flooring', iconName: 'Grid', description: 'Granite, vitrified tiles, marble laying, floor leveling', active: true },
  { id: 'cat-painting', name: 'Painting & Screeding', iconName: 'Paintbrush', description: 'Interior/exterior decorative painting, wall screeding, texturing', active: true },
  { id: 'cat-welding', name: 'Welding & Metalwork', iconName: 'Flame', description: 'Security burglary gates, carports, iron rails, metal tanks', active: true },
  { id: 'cat-masonry', name: 'Masonry & Bricklaying', iconName: 'Boxes', description: 'Block moulding, building foundation, plastering, German floor', active: true },
  { id: 'cat-auto-mechanic', name: 'Auto Mechanics', iconName: 'Car', description: 'Engine overhaul, computerized vehicle diagnostics, suspension', active: true },
  { id: 'cat-motorcycle', name: 'Motorcycle & Bajaj Repair', iconName: 'Bike', description: 'Boxer, TVS, Haojue, and Keke NAPEP engine mechanics', active: true },
  { id: 'cat-phone-repair', name: 'Phone & Tablet Repair', iconName: 'Smartphone', description: 'Screen replacement, board IC microsoldering, battery issues', active: true },
  { id: 'cat-computer', name: 'Computer & Laptop Repair', iconName: 'Laptop', description: 'OS installation, board repair, RAM upgrade, printer setup', active: true },
  { id: 'cat-tailoring', name: 'Tailoring & Native Wear', iconName: 'Scissors', description: 'Benue traditional attire, senators, agbada, kaftans', active: true },
  { id: 'cat-fashion', name: 'Fashion Design', iconName: 'Sparkles', description: 'Bridal gowns, bespoke corporate wear, Ankara designs', active: true },
  { id: 'cat-hairdressing', name: 'Hairdressing & Braiding', iconName: 'Smile', description: 'Ghana weaving, knotless braids, wig revamping, fixing', active: true },
  { id: 'cat-barbing', name: 'Barbing & Grooming', iconName: 'Scissors', description: 'Precision fades, beard grooming, dye, hair treatment', active: true },
  { id: 'cat-makeup', name: 'Makeup & Gele Tying', iconName: 'Eye', description: 'Traditional wedding glam, photoshoot, gele styling', active: true },
  { id: 'cat-catering', name: 'Catering & Event Cooking', iconName: 'Utensils', description: 'Benue bush meat delicacies, jollof, small chops, wedding feast', active: true },
  { id: 'cat-photography', name: 'Photography', iconName: 'Camera', description: 'Portraits, studio shoots, event coverage, drone capture', active: true },
  { id: 'cat-videography', name: 'Videography', iconName: 'Video', description: 'Wedding film, documentations, corporate video, editing', active: true },
  { id: 'cat-cleaning', name: 'Cleaning & Janitorial', iconName: 'Sparkle', description: 'Post-construction cleanup, deep home disinfection, sofas', active: true },
  { id: 'cat-laundry', name: 'Laundry & Dry Cleaning', iconName: 'Shirt', description: 'Starch pressing, suit dry cleaning, rug washing', active: true },
  { id: 'cat-appliance', name: 'Appliance Repair', iconName: 'Tv', description: 'Microwaves, washing machines, blenders, electric cookers', active: true },
  { id: 'cat-printing', name: 'Printing & Signage', iconName: 'Printer', description: 'Flex banners, customized souvenirs, business cards, rollups', active: true },
  { id: 'cat-graphics', name: 'Graphic Design & Branding', iconName: 'PenTool', description: 'Logos, flyers, social media flyers, 3D mockups', active: true },
  { id: 'cat-event-decor', name: 'Event Decoration', iconName: 'Flower', description: 'Canopy dressing, stage lighting, floral arrangements', active: true },
  { id: 'cat-interior-decor', name: 'Interior Decoration', iconName: 'Home', description: 'Wallpapers, curtains, modern light fixtures, space styling', active: true },
  { id: 'cat-construction', name: 'Building Construction', iconName: 'Building', description: 'Full architectural drawings, project supervision, structural works', active: true },
  { id: 'cat-gardening', name: 'Gardening & Landscaping', iconName: 'TreePine', description: 'Grass trimming, hedge pruning, interlocking pavement grass', active: true },
  { id: 'cat-pest-control', name: 'Pest Control & Fumigation', iconName: 'ShieldAlert', description: 'Termite extermination, mosquito & snake repellent fumigation', active: true },
  { id: 'cat-moving', name: 'Moving & Relocation', iconName: 'Truck', description: 'House luggage loading, truck transport across Makurdi & Benue', active: true },
  { id: 'cat-other', name: 'Other Artisan Services', iconName: 'MoreHorizontal', description: 'General handyman, shoe making, bag repairs, and special skills', active: true },
];
